// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3dKPdxJxSV4zQW8auNy5oYyY-hfOY21c',
    appId: '1:481320692502:web:74f0445ba74f1407057e37',
    messagingSenderId: '481320692502',
    projectId: 'loginwith-9010a',
    authDomain: 'loginwith-9010a.firebaseapp.com',
    storageBucket: 'loginwith-9010a.appspot.com',
    measurementId: 'G-CM6C1WM56K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr10ZNRBlq5csTbNDlM1ejaocKWzuBLFI',
    appId: '1:481320692502:android:117e3c9c608a76cf057e37',
    messagingSenderId: '481320692502',
    projectId: 'loginwith-9010a',
    storageBucket: 'loginwith-9010a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5a8SzJaDZ3NIRKJtzVIux0THEdSdTAU',
    appId: '1:481320692502:ios:26d5180bbba7ebed057e37',
    messagingSenderId: '481320692502',
    projectId: 'loginwith-9010a',
    storageBucket: 'loginwith-9010a.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO5a8SzJaDZ3NIRKJtzVIux0THEdSdTAU',
    appId: '1:481320692502:ios:26d5180bbba7ebed057e37',
    messagingSenderId: '481320692502',
    projectId: 'loginwith-9010a',
    storageBucket: 'loginwith-9010a.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3dKPdxJxSV4zQW8auNy5oYyY-hfOY21c',
    appId: '1:481320692502:web:ad58c96380c07b97057e37',
    messagingSenderId: '481320692502',
    projectId: 'loginwith-9010a',
    authDomain: 'loginwith-9010a.firebaseapp.com',
    storageBucket: 'loginwith-9010a.appspot.com',
    measurementId: 'G-FQ9ZS2JP5S',
  );
}
